### ISSUE TITLE
glstrings of invalid alleles should return and empty string but sometimes return +

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#100]
```(Pdb) ard.redux_gl("DR04+DR03", 'lg')
'+'
(Pdb) ard.redux_gl("DR04+assDR03", 'lg')
''
```
This is probably because the first example looks like serology.  It is invalid serology but returning a + alone is not legit.

Overall error handing needs to be reworked but this is causing a problem with the international donor/recip validation data

**Comment by pbashyal-nmdp** [comment]
Is that the right example ? It returns `''`
```
>>> ard.redux_gl("DR04+assDR03", 'lg')
''
>>>
```

**Comment by mmaiers-nmdp** [comment]
paste error

`ard.redux_gl("DR04+DR03", 'lg')`

**Comment by mmaiers-nmdp** [comment]
The full example is:
```
(Pdb) ard.redux_gl("DR04+DR03", 'lg')
'+'
(Pdb) ard.redux_gl("DR04+assDR03", 'lg')
''
```
