### ISSUE TITLE
setting pyard.max_cache_size = 1_000_000 doesn't seem to change it

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#113]
setting pyard.max_cache_size = 1_000_000 doesn't seem to change it

**Comment by pbashyal-nmdp** [comment]
The lru_cache function is resolved when ARD object is imported in [__init__.py](https://github.com/nmdp-bioinformatics/py-ard/blob/16d18e652441711b1e7fcbcfe35ba346db7393f0/pyard/__init__.py#L24) Should be resolved with change to #87

**Comment by pbashyal-nmdp** [comment]
Fixed with #215
