### ISSUE TITLE
Two-field reduction from three-field or full-field WHO

### ISSUE THREAD

**Issue by lgragert** [nmdp-bioinformatics/py-ard#120]
Requires loading complete WHO allele list into memory determine if expression characters should propagate downward.

`DRB5*01:08N` is valid nomenclature, per Steve Marsh.

`DRB5*01:08:01N` and `DRB5*01:08:02N` are currently the only allelic variants of `DRB5*01:08N`.

**Comment by pbashyal-nmdp** [comment]
Would this be solved by using the unambiguous reduction mode ? #121

**Comment by lgragert** [comment]
Agreed, I'll close this issue and add a note in the U2 issue.
