### ISSUE TITLE
some broad/split relationships are missing

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#127]
The B14: B64/B65 broad split relationship is missing.
This was reported by @zuriyaAnsbacher

Yet ard.redux_gl('B14', 'lgx') gives the right answer (but for the wrong reason)

An input of B14 expands to all alleles `B*14:03` or above but some of these alleles (like `B*14:81`) are in the `B*14:01:01G` group and some of these like B*14:89 are in the `B*14:02:01G` group so after ARD reduction this picks up `B*14:01` and `B*14:02`. 

Note the difference with lgx (includes B*14:01 and B*14:02) but not W

`B14 expanded with lgx
B*14:01/B*14:02/B*14:03/B*14:04/B*14:05/B*14:06/B*14:08/B*14:09/B*14:10/B*14:11/B*14:12/B*14:13/B*14:14/B*14:15/B*14:16/B*14:17/B*14:18/B*14:19/B*14:20/B*14:21/B*14:22/B*14:23/B*14:24/B*14:25/B*14:26/B*14:27/B*14:28/B*14:29/B*14:30/B*14:31/B*14:32/B*14:33/B*14:34/B*14:35/B*14:36/B*14:37/B*14:38/B*14:39/B*14:40/B*14:42/B*14:43/B*14:44/B*14:45/B*14:46/B*14:47/B*14:48/B*14:49/B*14:50/B*14:51/B*14:52/B*14:53/B*14:54/B*14:55/B*14:56/B*14:57/B*14:58/B*14:59/B*14:60/B*14:62/B*14:63/B*14:65/B*14:66/B*14:68/B*14:70Q/B*14:71/B*14:73/B*14:74/B*14:75/B*14:77/B*14:82/B*14:83/B*14:86/B*14:87/B*14:88/B*14:90/B*14:93/B*14:94/B*14:95/B*14:96/B*14:97/B*14:99/B*14:102`

`B14 expanded with W
B*14:03/B*14:04/B*14:05/B*14:06:01/B*14:06:02/B*14:08:01/B*14:08:02/B*14:09/B*14:10/B*14:11/B*14:12/B*14:13/B*14:14/B*14:15/B*14:16/B*14:17/B*14:18/B*14:19/B*14:20/B*14:21/B*14:22/B*14:23/B*14:24/B*14:25/B*14:26/B*14:27/B*14:28/B*14:29/B*14:30/B*14:31/B*14:32/B*14:33/B*14:34/B*14:35/B*14:36/B*14:37/B*14:38/B*14:39/B*14:40/B*14:42/B*14:43/B*14:44/B*14:45/B*14:46/B*14:47/B*14:48/B*14:49/B*14:50/B*14:51/B*14:52/B*14:53/B*14:54/B*14:55/B*14:56/B*14:57/B*14:58/B*14:59/B*14:60/B*14:61/B*14:62/B*14:63/B*14:64/B*14:65/B*14:66/B*14:67/B*14:68/B*14:70Q/B*14:71/B*14:73/B*14:74/B*14:75/B*14:77/B*14:80/B*14:81/B*14:82/B*14:83/B*14:84/B*14:86/B*14:87/B*14:88/B*14:89/B*14:90/B*14:91/B*14:92/B*14:93/B*14:94/B*14:95/B*14:96/B*14:97/B*14:98/B*14:99/B*14:102`

Remediation:
- review and update the *hard coded* serology broad/split mappings in `pyard/broad_splits.py`
- fix and add tests including making sure that `B*14:01:01:01` and `B*14:02:01:01` are included in ard.redux_gl('B14', 'W')

**Comment by pbashyal-nmdp** [comment]
Switch to using https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/rel_ser_ser.txt for the serology mapping instead of hardcoding the mapping.
