### ISSUE TITLE
accept DRB4*01:03:01N 

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#130]
This is a category of alleles that are:
* not valid as is
* if the expression character is removed, they are valid but only if there is a longer name with the same expression character
* **reduce** (lg, lgx, G) based on removing the expression character
* **expand** (exon, W) by returning the alleles in the expansion with the same expression character
* `DRB4*01:03:01N`=> `DRB4*01:03:01:02N/DRB4*01:03:01:13N`

redux_gl - treat as valid (as long as the version with the expression character removed is valid AND if there is also a longer named allele with the same expression character)
redux - for G, lg, lgx, remove expression character
redux - for exon, W return the subset of alleles in the expansion with the same expression character

**Comment by pbashyal-nmdp** [comment]
Closed by #136
