### ISSUE TITLE
Ambiguous allele duplicated in the final result

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/py-ard#135]
Fails to collapse an allele that's also in ambiguous string. Reported by CVG.

For `C*02:ACMGS` allele code, it's expanding to `['C*02:02', 'C*02:29', 'C*02:69', 'C*02:70', 'C*02:83']` and reducing to:
```
'C*02:02/C*02:10'
'C*02:02'
'C*02:02'
'C*02:02'
'C*02:02'
```
It's collapsing all the similar reduced ones  and producing `'C*02:02/C*02:02/C*02:10'` as it sees `'C*02:02/C*02:10'` different from `C*02:02`.

**py-ard** should collapse once more after all the reductions are gathered.

**Comment by mmaiers-nmdp** [comment]
Indeed.  Now that it can happen that a single two field allele can be in multiple G-groups (and lgx groups) this needs to be deduped.

```pyard --gl "C*02:02" -r "lgx"
C*02:02/C*02:10
```
