### ISSUE TITLE
pyard-reduce-csv should output glstring

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#142]
pyard-reduce-csv should have an option to produce a glstring as output
it should also add loci if they are not there in the input

this is a common pattern: read tabular HLA without loci in the string => reduce => glstring output

**Comment by pbashyal-nmdp** [comment]
> it should also add loci if they are not there in the input

You can set ` "keep_locus_in_allele_name"` to `true` to output with loci.

**Comment by pbashyal-nmdp** [comment]
Closed duplicate #181
