### ISSUE TITLE
Add Performance Tests

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/py-ard#147]
Create performance tests.

From @mmaiers-nmdp 
> performance of py-ard has deteriorate substantially since late Dec (global convert takes over 1 week vs < 1 hr before). I think there is something not working in the caching/memoizing but I haven't had a chance to look into it.
>We should include performance tests .

**Comment by mmaiers-nmdp** [comment]
The issue appears to be that this code vignette does not do what is intended:
```
 # Set the lru cache size with
 # >>> import pyard
 # >>> pyard.max_cache_size = 1_000_000
 # >>> ard = pyard.ARD()
 ```

The only way to convert large datasets (EM extract) is to change max_cache_size **within pyard/pyard.py**.
If this is done (e.g. 5_000_000) then a datafile of 40M records can be processed in a matter of 2hr15min.

Setting the value as instructed above does not actually change the cache size which means the conversion process will takes weeks to months.

It is tempting to have a larger default value but py-ard is used in server application where having a very large cache is a problem. 


So the workaround is the modify pyard/pyard.py directly and keep it small in the base repo.
In the longe term, to resolve this issue we need to find a way to make this configurable.

**Comment by pbashyal-nmdp** [comment]
There's #113 that's related. I've set it for `0.9.x` timeline because it requires change in the API. Yes, currently you have to modify the code.
