### ISSUE TITLE
pyARD should handle serologic nomenclature

### ISSUE THREAD

**Issue by lgragert-nmdp** [nmdp-bioinformatics/py-ard#16]
Would be useful to expand serology types using WMDA rel_ser_dna.txt file then collapse to a GL string with ARD reduction.

Trying to expand HapLogic CT validation data that looks like this.

9639949 1       CAU                     0       2       32      0       51      38      1       11:01   13:01   0       2       X       1       06:03   03:01   1       01:01   02:02   0                       0                       502377203       CAU                     0       2       32      0       0       38      51      0       1       11:XX   13:XX   0       0       2       4       0       0       3       6       0       1       01:GHT          0       0                       0       0                       0

**Comment by mmaiers-nmdp** [comment]
I agree.  

I also think pyARD is a better home for 

- the g2gl functionality from grimm
- the squashing of "|" from grimm/g2gl

**Comment by mmaiers-nmdp** [comment]
This table should be used https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/rel_dna_ser.txt is updated quarterly and the specific versions have the corresponding URL e.g. https://raw.githubusercontent.com/ANHIG/IMGTHLA/3390/wmda/rel_dna_ser.txt
