### ISSUE TITLE
Implement a two-field redux (w/o ARD rollup)

### ISSUE THREAD

**Issue by lgragert** [nmdp-bioinformatics/py-ard#162]
Here are the current redux categories:

```
A*01:04N   lg   A*01:01g
A*01:04N   lgx   A*01:01
A*01:04N   G   A*01:01:01G
A*01:04N   exon   A*01:04:01
A*01:04N   W   A*01:04:01:01N/A*01:04:01:02N
```

I would like to request a two-field redux, without any ARD rollup, where the allele names `A*01:04N`, `A*01:04:01N`,`A*01:04:01:01N` would redux to `A*01:04N`.

Call it "twofield" or "2F" or something like that.

This redux mode would truncate the allele name to two fields while propagating down the expression characters to two-field, if the expression characters are all the same at three-field and full-field level.

This level of resolution is appropriate for virtual crossmatch applications based on full HLA protein sequences (HLA as an antibody epitope instead of HLA+peptide as a T-cell epitope).

**Comment by mmaiers-nmdp** [comment]
This sound a lot like the new U2 redux mode.

**Comment by lgragert** [comment]
Possible to make a U2 redux of the latest pull to run haplotype freqs?

**Comment by pbashyal-nmdp** [comment]
`U2` seems to do the trick:

```
$ pyard --gl "A*01:04N" -r U2
A*01:04N
$ pyard --gl "A*01:04:01N" -r U2
A*01:04N
$ pyard --gl "A*01:04:01:01N" -r U2
A*01:04N
$ pyard --gl "A*01:04N/A*01:04:01N/A*01:04:01:01N" -r U2
A*01:04N
```

**Comment by lgragert** [comment]
This is great - I'm going to use the U2 redux to remediate the CPRA genotype frequency file. Would like to have a two-field pull at some point, but not urgent.

**Comment by pbashyal-nmdp** [comment]
More detail is on the Issue that started `U2`: https://github.com/nmdp-bioinformatics/py-ard/issues/121

**Comment by mmaiers-nmdp** [comment]
Yes, it should be just changing one flag.
I guess you want the shortnulls to do the right thing as well.
I’ll check into it.

**Comment by lgragert** [comment]
Yup, the CPRA extract was based on the three-field 'exon' rollup, which I truncated to two-field but did not have the shortnulls correct. 'U2' seems to have the shortnulls correct, but it would be good to have an extract to run the pipeline start-to-finish.
