### ISSUE TITLE
cmdline tool fails when switching between versions

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#170]
from a clean pip install py-ard running with a different HLADB version fails:
```
(venv) A0506268:tmp mmaiers$ venv/bin/pyard -v 3.48.0 --gl "DQB1*02:02" -r lgx
DQB1*02:01
(venv) A0506268:tmp mmaiers$ venv/bin/pyard -v 3.47.0 --gl "DQB1*02:02" -r lgx
Traceback (most recent call last):
  File "/Users/mmaiers/tmp/venv/bin/pyard", line 64, in <module>
    ard = pyard.ARD(imgt_version)
  File "/Users/mmaiers/tmp/venv/lib/python3.9/site-packages/pyard/pyard.py", line 105, in __init__
    dr.generate_alleles_and_xx_codes_and_who(self.db_connection, imgt_version, self.ars_mappings)
  File "/Users/mmaiers/tmp/venv/lib/python3.9/site-packages/pyard/data_repository.py", line 214, in generate_alleles_and_xx_codes_and_who
    shortnulls = db.load_dict(db_connection, 'shortnulls', 
  File "/Users/mmaiers/tmp/venv/lib/python3.9/site-packages/pyard/db.py", line 288, in load_dict
    cursor.execute(select_all_query)
sqlite3.OperationalError: no such table: shortnulls
```

This may have been introduced with the "shortnulls" table as the error suggests

**Comment by pbashyal-nmdp** [comment]
This is most likely trying to use a sqlite3 file that was created before the `shortnull` changes. Can you delete `~/.pyard/pyard-3470.sqlite3` and try it again ? It should rebuild with `shortnull` table.

**Comment by mmaiers-nmdp** [comment]
Wow that was hard to find.  Its ~/.pyard.  I had no idea.  I just removed **14 sqlite3 databases**. The file for 3470 is 480MB!!!

I'm probably not the typical user but we need to:
1. implement the feature that prevents this kind of error from happening by forcing a re-creation of the sqlite database whenever there is a new release of pyard.  Maybe the current version of pyard could be a subfolder under ~/.pyard
2. On the other hand this will only multiply the number of copies of the sqlite database because, if we do implement pyard-version-specific folders then I'll probably have even more 1/2 Gig files laying around
3. another thing we could do is at least expose the database location as a parameter to the cmdline version

**Comment by pbashyal-nmdp** [comment]
That seems to fix it.
```
$ rm ~/.pyard/pyard-3470.sqlite3

$ pyard -v 3.47.0 --gl "DQB1*02:02" -r lgx
DQB1*02:01
```

**Comment by pbashyal-nmdp** [comment]
The `pyard-import` helps you deal with generating/updating data.

```
$ pyard-import --help
usage: [--db-version <IMGT DB Version>]

        [--data-dir <directory for db file>]

        [--v2-to-v3-mapping <V2 to V3 mapping CSV file>]

py-ard tool to generate reference SQLite database. Allows updating db with custom V2 to V3 mappings.

optional arguments:
  -h, --help            show this help message and exit
  --db-version IMGT_VERSION
  --data-dir DATA_DIR
  --v2-to-v3-mapping V2_V3_MAPPING
  --refresh-mac
  --re-install
```
Yes, it'd be a good idea to add `--data-dir` option to `pyard` command.

**Comment by pbashyal-nmdp** [comment]
There's also `pyard-status` that tells you all the databases you have and the tables.

**Comment by pbashyal-nmdp** [comment]
These tools are documented in [command-line-tools](https://github.com/nmdp-bioinformatics/py-ard#command-line-tools) section of the README.
