### ISSUE TITLE
GLString format - is a locus prefix necessary for each '/'-delimited allele?

### ISSUE THREAD

**Issue by rsajulga-nmdp** [nmdp-bioinformatics/py-ard#176]
Should we be able to support GL strings that don't have a locus for each delimited allele?

**What works**
```
ard.redux_gl('B*07:02/B*07:06', 'lgx')
```
`'B*07:02/B*07:05'`

**What doesn't**
```
ard.redux_gl('B*07:02/07:06', 'lgx')
```
`Invalid Allele: 07:06 is not a valid Allele`

**Comment by pbashyal-nmdp** [comment]
I don't think we would want to support that. If you have that kind of data, you can preprocess that with something like:
```python
>>> al = 'B*07:02/07:06/07:03/07:31'
>>> locus = al.split('*')[0]
>>> new_al = al.replace('/', f"/{locus}*")
>>> new_al
'B*07:02/B*07:06/B*07:03/B*07:31'
```
and then use `py-ard`
```
>>> import pyard
>>> ard = pyard.ARD()
>>> ard.redux_gl(new_al, 'lgx')
'B*07:02/B*07:03/B*07:05/B*07:31'
>>>
```

**Comment by rsajulga-nmdp** [comment]
Okay. Makes sense. Thank you. I'll go with the pre-processing then.
