### ISSUE TITLE
pyard-reduce-csv config cant turn off compression

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#180]
`Valid compression types are ['infer', None, 'bz2', 'gzip', 'tar', 'xz', 'zip', 'zstd']`
There is no way to have None in the config.json
Also the program dies if apply_compression is not in config therefore no way to turn compression off

**Comment by pbashyal-nmdp** [comment]
You want to use `null` in the JSON config.
https://github.com/nmdp-bioinformatics/py-ard/tree/master/extras#compression-options
