### ISSUE TITLE
DPB1*57:01:01G Error

### ISSUE THREAD

**Issue by rsajulga-nmdp** [nmdp-bioinformatics/py-ard#182]
#### This works:
```
ard.redux_gl('DPB1*01:01:01G', 'G')
```
'DPB1*01:01:01G'

---

#### But this doesn't:
```
ard.redux_gl('DPB1*57:01:01G', 'G')
```
InvalidAlleleError                        Traceback (most recent call last)
Cell In [413], line 1
----> 1 ard.redux_gl('DPB1*57:01:01G', 'G')

File ~/Library/CloudStorage/OneDrive-BeTheMatch/Code/dpb1-expression/analysis/venv/lib/python3.9/site-packages/pyard/pyard.py:359, in ARD.redux_gl(self, glstring, redux_type)
    356 if self._config["reduce_shortnull"] and self.is_shortnull(glstring):
    357     return self.redux_gl("/".join(self.shortnulls[glstring]), redux_type)
--> 359 return self.redux(glstring, redux_type)

File ~/Library/CloudStorage/OneDrive-BeTheMatch/Code/dpb1-expression/analysis/venv/lib/python3.9/site-packages/pyard/pyard.py:232, in ARD.redux(self, allele, redux_type)
    230     return allele
    231 else:
--> 232     raise InvalidAlleleError(f"{allele} is an invalid allele.")

InvalidAlleleError: Invalid Allele: DPB1*57:01:01 is an invalid allele.

**Comment by pbashyal-nmdp** [comment]
The reduced version of `DPB1*01:01:01G` is `DPB1*01:01:01` which is a valid allele. 
```
>>> ard.isvalid('DPB1*01:01:01G')
True
>>> ard.isvalid('DPB1*01:01:01')
True
```
But the reduced version of `DPB1*57:01:01G` -> `DPB1*57:01:01` is not a valid allele.
```
>>> ard.isvalid('DPB1*57:01:01G')
True
>>> ard.isvalid('DPB1*57:01:01')
False
```

**Comment by mmaiers-nmdp** [comment]
@rsajulga-nmdp I guess you need to catch this exception and treat this as an invalid allele.
I'll close this one.
