### ISSUE TITLE
Serology as Array when Sister Serotypes exist

### ISSUE THREAD

**Issue by SeanStagg-NMDP** [nmdp-bioinformatics/py-ard#194]
Currently, `pyard --gl 'A66' -r lgx` returns `A*66:01/A*66:02/A*66:04/A*66:05/A*66:06/A*66:07/A*66:09/A*66:10/A*66:11/A*66:12/A*66:13/A*66:14/A*66:15/A*66:16/A*66:18/A*66:19/A*66:20/A*66:21/A*66:22/A*66:23/A*66:24/A*66:25/A*66:26Q/A*66:30/A*66:32/A*66:33/A*66:35/A*66:37/A*66:40/A*66:41/A*66:42/A*66:43/A*66:44/A*66:45/A*66:47`, however I am not sure that is 100% valid. An array with "sister serotypes" may be better when the input is serology.
https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/rel_ser_ser.txt / https://hla.alleles.org/antigens/broads_splits.html 

See also https://en.wikipedia.org/wiki/HLA-A66

**Comment by pbashyal-nmdp** [comment]
`pyard` looks at `rel_dna_ser.txt` mapping to figure out the G groups for serology. https://hla.alleles.org/wmda/index.html

**Comment by pbashyal-nmdp** [comment]
We do have broad/splits defined for serology in [pyard/broad_splits.py](https://github.com/nmdp-bioinformatics/py-ard/blob/dbfac4dd3471e6a0665ced7d71b2b5a0bbe058b8/pyard/broad_splits.py#L47). The splits are not distributed among other splits(sisters).  For example, reducing the broad `A10` gives you all the splits("sisters").

`pyard --gl "A10" -r lgx`

Gives you:

`A*25:01:01G/A*25:01:02/A*25:01:03/A*25:01:04/A*25:01:05/A*25:01:06/A*25:01:07/A*25:01:08/A*25:01:09/A*25:01:10/A*25:01:11/A*25:01:12/A*25:01:14/A*25:01:16/A*25:01:17/A*25:01:19/A*25:02/A*25:03/A*25:04/A*25:05/A*25:06/A*25:08/A*25:09/A*25:10/A*25:11/A*25:13/A*25:14/A*25:15/A*25:16/A*25:17/A*25:18/A*25:19:01/A*25:19:02/A*25:20/A*25:21/A*25:22/A*25:23/A*25:24/A*25:25/A*25:26/A*25:27:01/A*25:27:02/A*25:28/A*25:29/A*25:30/A*25:31/A*25:32/A*25:33/A*25:34/A*25:35/A*25:36/A*25:37/A*25:38/A*25:39/A*25:40/A*25:41/A*25:43/A*25:44/A*25:45/A*25:46/A*25:47/A*25:48/A*25:50/A*25:51/A*25:52/A*25:53/A*25:54/A*25:55/A*25:56/A*25:57/A*25:58/A*25:59/A*25:61/A*25:64/A*25:65/A*25:66/A*25:67/A*25:70/A*25:71/A*25:72/A*25:73/A*25:74/A*25:75/A*25:76:01/A*25:76:02/A*25:77/A*25:78/A*25:79/A*25:80/A*25:81/A*25:82/A*25:83/A*25:84/A*26:01:01G/A*26:01:02/A*26:01:03/A*26:01:04/A*26:01:05/A*26:01:06/A*26:01:08/A*26:01:09/A*26:01:10/A*26:01:11/A*26:01:12/A*26:01:13/A*26:01:14/A*26:01:15/A*26:01:16/A*26:01:17/A*26:01:18/A*26:01:19/A*26:01:20/A*26:01:21/A*26:01:22/A*26:01:23/A*26:01:24/A*26:01:26/A*26:01:27/A*26:01:28/A*26:01:29/A*26:01:30/A*26:01:31/A*26:01:33/A*26:01:34/A*26:01:36/A*26:01:37/A*26:01:38/A*26:01:39/A*26:01:41/A*26:01:42/A*26:01:45/A*26:01:48/A*26:01:50/A*26:01:51/A*26:01:52/A*26:01:53/A*26:01:54/A*26:01:57/A*26:01:59/A*26:01:60/A*26:01:61/A*26:01:62/A*26:01:63/A*26:01:64/A*26:01:65/A*26:01:66/A*26:01:69/A*26:01:71/A*26:01:72/A*26:01:74/A*26:01:77/A*26:02:01/A*26:02:02/A*26:03:01G/A*26:03:03/A*26:04/A*26:05/A*26:06/A*26:07:01/A*26:07:02/A*26:08:01G/A*26:08:02/A*26:08:03/A*26:09/A*26:10/A*26:12:01G/A*26:13/A*26:14/A*26:15/A*26:16/A*26:17/A*26:18/A*26:19/A*26:20:01/A*26:20:02/A*26:21/A*26:22/A*26:23/A*26:27/A*26:28/A*26:29/A*26:30/A*26:31/A*26:32/A*26:33/A*26:34/A*26:35/A*26:36/A*26:37/A*26:38/A*26:39/A*26:40/A*26:41/A*26:42/A*26:43:01/A*26:43:02/A*26:45/A*26:46/A*26:47/A*26:48/A*26:49/A*26:50/A*26:51/A*26:52/A*26:53/A*26:54/A*26:55/A*26:57/A*26:58/A*26:59/A*26:61/A*26:62/A*26:63/A*26:64/A*26:65/A*26:66/A*26:67/A*26:68/A*26:69/A*26:70/A*26:72/A*26:73/A*26:74/A*26:75/A*26:76/A*26:77/A*26:78/A*26:79/A*26:80/A*26:81/A*26:83/A*26:84/A*26:85/A*26:86/A*26:87/A*26:88/A*26:89/A*26:90/A*26:91/A*26:92/A*26:93/A*26:94/A*26:95/A*26:96/A*26:97/A*26:100/A*26:101/A*26:102/A*26:103/A*26:104/A*26:105/A*26:106/A*26:108/A*26:109/A*26:110/A*26:111/A*26:112:01/A*26:112:02/A*26:113/A*26:114/A*26:115/A*26:116/A*26:118/A*26:119/A*26:120/A*26:121/A*26:122/A*26:123/A*26:124/A*26:125/A*26:126/A*26:128/A*26:129/A*26:130/A*26:131/A*26:132/A*26:133/A*26:134/A*26:135/A*26:136/A*26:137/A*26:138/A*26:139/A*26:140/A*26:141/A*26:142/A*26:143/A*26:144/A*26:146/A*26:147/A*26:148/A*26:149/A*26:150/A*26:151/A*26:152/A*26:153/A*26:154/A*26:155/A*26:156/A*26:158/A*26:159/A*26:165/A*26:169/A*26:170/A*26:171/A*26:172/A*26:173/A*26:174/A*26:175/A*26:176/A*26:177/A*26:178/A*26:181/A*26:182/A*26:184/A*26:188/A*26:189/A*26:190/A*26:192/A*26:193/A*26:194/A*26:195/A*26:196/A*26:197/A*26:198/A*26:200/A*26:204:01G/A*26:205/A*26:207/A*26:211/A*26:212/A*26:213/A*26:214/A*26:215/A*26:216/A*26:217/A*26:218/A*26:219/A*26:221/A*26:224/A*26:225/A*26:226/A*26:227/A*26:229/A*34:01:01G/A*34:01:02/A*34:01:03/A*34:01:05/A*34:01:07/A*34:02:01G/A*34:02:02/A*34:02:03/A*34:02:04/A*34:02:05/A*34:03/A*34:04/A*34:05/A*34:06/A*34:07/A*34:08/A*34:09/A*34:11/A*34:12/A*34:13/A*34:14/A*34:15/A*34:16/A*34:17/A*34:19/A*34:20/A*34:21/A*34:22/A*34:23/A*34:24/A*34:25/A*34:27/A*34:28/A*66:01:01G/A*66:01:02/A*66:01:03/A*66:01:04/A*66:01:05/A*66:01:07/A*66:02:01G/A*66:03:01G/A*66:04/A*66:05/A*66:06/A*66:07/A*66:09/A*66:10/A*66:11/A*66:12/A*66:13/A*66:14/A*66:15/A*66:16/A*66:18/A*66:19/A*66:20/A*66:21/A*66:22/A*66:23/A*66:24/A*66:25/A*66:26Q/A*66:30/A*66:32/A*66:33/A*66:35/A*66:37/A*66:40/A*66:41/A*66:42/A*66:43/A*66:44/A*66:45/A*66:47`

I just fixed an issue for DNA broad/splits where this was the issue. See #191

**Comment by SeanStagg-NMDP** [comment]
Is it more valid for `pyard --gl "A66" -r lgx` (and 25/26/34) to have the same output as `pyard --gl "A10" -r lgx`?

**Comment by pbashyal-nmdp** [comment]
Closing this issue and opened new issue #195 to retrieve broad/split info.
