### ISSUE TITLE
stop using ~/.pyard

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#198]
The current ~/.pyard/pyard-Latest.sqlite3 is 544M.

I think putting such a large file in the users home director is impolite behavior.

Running py-ard across a handful of database version will lead to the silent and permanent occupation of several GB under the user's home directory.  Lets not do that.

Options:
1. Why not keep this installed under the package?  
2. Use tempfiles: https://docs.python.org/3/library/tempfile.html
3. Allow the user to configure the location (decide if they want it to be in a temporary or permanent storage location

I'm a bit biased since I am a heavy user and py-ard is currently undergoing many changes but I think the tmpfiles should be in temporary storage by default.  If a user wants to set them somewhere permanent, they can do that.  The current behavior of using permanent storage silently should be changed.

**Comment by pbashyal-nmdp** [comment]
> Why not keep this installed under the package?

These files are generated at runtime. Which version of db would we include ? Also PyPi filesize limit is 60MB

> Use tempfiles: https://docs.python.org/3/library/tempfile.html

The temp files are cleared when a computer reboots or whenever OS feels memory/swap pressure. These take a while to build so would be good to have it in a more permanent place. But temp space is supported with `data-dir` option, see below.

> Allow the user to configure the location (decide if they want it to be in a temporary or permanent storage location

Agree that there should be an option to specify an alternative location. There's a `datadir` parameter you can use in `pyard.ARD()`. `pyard-import` has `--data-dir` option as well. Looks like `pyard` and `pyard-reduce-csv` doesn't, I'll create an issue for that.

> I think putting such a large file in the users home director is impolite behavior.
Running py-ard across a handful of database version will lead to the silent and permanent occupation of several GB under the user's home directory. Lets not do that.

I agree that it should notify you where the file is created when creating the db.

**Comment by pbashyal-nmdp** [comment]
Created an issue to change the default save directory. #202
