### ISSUE TITLE
Implement P group redux type

### ISSUE THREAD

**Issue by lgragert** [nmdp-bioinformatics/py-ard#200]
We're wanting to include P-group categories in a column for the HLA Dictionary project, which is a redux type not yet supported by py-ard.

https://hla.alleles.org/alleles/p_groups.html

We hypothesize that alleles in the same P group would be more likely to have similar serologic reactivity than alleles in different P groups.

This is a different use case that doesn't involve processing an actual HLA typing.

**Comment by pbashyal-nmdp** [comment]
We just removed the p_group table because it wasn't being used for reduxtion. #173

**Comment by pbashyal-nmdp** [comment]
Added to Post 1.0 release milestone for now.

**Comment by pbashyal-nmdp** [comment]
@lgragert 
This is now part of the [2nd Release Candidate for 1.0](https://github.com/nmdp-bioinformatics/py-ard/releases/tag/1.0.0rc2)
Install with:
```
pip install py-ard --pre
```
or 
```
brew tap nmdp-bioinformatics/tap
brew install py-ard
```

It now accepts `P` reduction mode.

```
 $ pyard --gl 'A*02:01:01:03' -r "P"        
A*02:01P
```
