### ISSUE TITLE
Change default cache directory

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/py-ard#202]
Currently default cache directory is `~/.pyard`, a hidden directory on unix systems. Change it to `~/pyard/` as to make it visible.
Related #198

**Comment by pbashyal-nmdp** [comment]
Add a `README` in the directory to explain what those files are.

**Comment by mmaiers-nmdp** [comment]
I think it should be in a temporary storage location. not the users home directory (hidden or unhidden) by default.  If a user wants to keep these files in their home directory they should explicitly have to "opt in" for this behavior.
