### ISSUE TITLE
Support exon redux using WMDA standards for two-field shortnulls

### ISSUE THREAD

**Issue by lgragert** [nmdp-bioinformatics/py-ard#223]
Per WMDA standards, `DRB4*01:03:01:02N` is often reported as `DRB4*01:03N`, which is invalid WHO nomenclature.

This feature of pyARD is critical to simulate HLA typings precisely as they are reported to WMDA.

**Comment by pbashyal-nmdp** [comment]
I think this works with `U2` reduction mode:
```python
ard.redux('DRB4*01:03:01:02N', 'U2')
'DRB4*01:03N'
```
`U2` mode does `lgx` for those that are not `U2`.

**Comment by pbashyal-nmdp** [comment]
Closing this as `U2` mode supports this use case.
