### ISSUE TITLE
Serology redux mode

### ISSUE THREAD

**Issue by lcreteig** [nmdp-bioinformatics/py-ard#229]
Would you consider adding a new redux mode to reduce an allele to its serological equivalent?

So for example:
- `A*01:01:01:01` -> A1
- `A*01:AABJE` -> A1
- `A*03:XX` -> A3
- `A*43:01/A*43:03` -> A43

Of course there's a few tricky cases in there where you can't just reduce to the first field:

- For some ambiguities the serological equivalent might differ, e.g. `B*15:01/B*15:02/B*15:03/B*15:04` could reduce to `B62`, `B72`, or `B75` 
- `B*13:03` -> `B13`, but `B*13:04` -> `B15`
- Some alleles have no (proven) serological equivalent

My use case for this is that I have a dataset where for each individual I have HLA typings in serological/antigen notation, but sometimes also at higher resolution. I'd like to reduce the alleles at higher resolution to their serological equivalents, to check whether it matches the lower-resolution typing.

I'd be curious to hear whether you've ever considered this and what your thoughts are. Even without this `py-ard` is already proving very useful to me; thanks a lot for making it available!

**Comment by pbashyal-nmdp** [comment]
@lcreteig 

Hello Leon,
We've just added support for serological reduction mode `S`. Could you test it on your code ? 
You can install from the current code with pip by:
```
pip install git+https://github.com/nmdp-bioinformatics/py-ard
```

You can then reduce it with `S` mode. Example:
```python
>>> import pyard
>>> ard = pyard.init()
>>> ard.redux('A*43:01/A*43:03', 'S')
'A43'
````

**Comment by lcreteig** [comment]
This looks great, thanks a lot for adding this feature! I'll make some time to play around with it and will try to get back to you next week at the latest.

**Comment by lcreteig** [comment]
Hi Pradeep,

Sorry for the delay in getting back to you; I finally got a chance to test it out and discuss with my PI. Overall I really like this feature and it works much more consistently than the lookup table I'd been using previously. We have a few points of feedback that you might still consider:

- We reduced all the alleles in the [Eurotransplant HLA tables](https://etrl.eurotransplant.org/resources/hla-tables/) with `py-ard` and checked for any differences, and found quite a few, mostly for HLA-B and DR. Sometimes this is simply a matter of debate, but we also found some that are potentially incorrect. Some examples:
  - `B*15:10` reduces to `B15/B62/B70/B71`; we think this should only be `B71(70)`
  - `B*15:11` reduces to `B15/B70/B75`; we think `B70` shouldn't be in there
  - `DRB1*07:34` doesn't reduce to anything (returns empty string); we think this should be a `DR7`
  -  Similarly, `DRB3*01:16` doesn't reduce to anything (returns empty string); we think this should be a `DR52`
 
  If you'd like I can send you the full list of examples. We checked the examples above against [Marsh et al. (2010)](https://doi.org/10.1111/j.1399-0039.2010.01466.x) and the current version of [rel_dna_ser.txt](https://github.com/ANHIG/IMGTHLA/blob/Latest/wmda/rel_dna_ser.txt).

- It could be useful to return both the split and the broad, but I'm not sure the `/` notation makes the most sense in this context. What `A25` (split) is to `A10` (broad) is not quite the same as what say `C*01:02` is to `C*01:03` in `C*01:02/C*01:03`. There's also no way to tell which is the split and which is the broad. You could also consider returning only splits if they exist, and otherwise the broad?

- Relatedly, if the input is already serology, the behaviour seems inconsistent. For example, `A25` is reduced to `A25/A10` (split and broad), but "reduction" of `DQ7` just returns itself, without the broad (`DQ3`).

Hope this is helpful and points to some potential areas for improvement. Thanks again!

**Comment by pbashyal-nmdp** [comment]
Thank you for the great feedback Leon. I've created a new issue #246 with it and we will look at the issues.
