### ISSUE TITLE
Redux with a "P" option does not return P-groups for two-field or three-field alleles

### ISSUE THREAD

**Issue by gbiagini** [nmdp-bioinformatics/py-ard#230]
When supplying a two-field allele to `ard.redux()` with the `"P"` option, the allele name is generally returned instead of the P-group. 

This may primarily affect alleles with additional four-field variants. 

For example, `ard.redux("B*07:02","P")` returns `B*07:02` (as does `ard.redux("B*07:02:01","P")`), while `ard.redux("B*07:02:01:01","P")` returns `B*07:02P`.
Similarly, `ard.redux("DRB1*01:01","P")` returns `DRB1*01:01` (as does `ard.redux("DRB1*01:01:01","P")`), while `ard.redux("DRB1*01:01:01:01","P")` returns `DRB1*01:01P`.

For an example of an allele without a four-field variant that behaves normally, `ard.redux("B*15:14","P")` returns `B*15:14P`, as expected. 

The expected behavior is that `ard.redux()` would return the same P-group for the two-field, three-field, and four-field equivalents of an allele.

The addition of P-groups to `ard.redux()` is very helpful and I thank you for this tool and for your time. I'm happy to aid in debugging if desired.

**Comment by pbashyal-nmdp** [comment]
Thanks Giovanni for the detailed examples. I'll take a look at what's causing the difference.

**Comment by pbashyal-nmdp** [comment]
Hello @gbiagini,

Just added the fix for P group mapping. Could you test it on your code ? 
You can install from the current code with pip by:
```
pip install git+https://github.com/nmdp-bioinformatics/py-ard
```

**Comment by gbiagini** [comment]
Hi @pbashyal-nmdp 

I tested the same alleles listed above with the same results. Maybe I'm missing something about getting the updated code?

I tried installing py-ard from the standard `pip install py-ard` as well as the command you provided, with the same results.

I also tried reinstalling the IMGT database for version 3.52.0, but that didn't seem to change anything either.

I tested both the Python module and CLI. Results of the CLI pasted below.

![image](https://github.com/nmdp-bioinformatics/py-ard/assets/48301124/c6634d41-0e32-4a7a-b6ba-15248583f240)

**Comment by pbashyal-nmdp** [comment]
It gives a correct answer on mine.
```
$ pyard -g "B*07:02" -r "P"
B*07:02P
```
It's not published yet(hopefully soon) so you can't do `pip install py-ard` yet.

Can you run `pyard-status` command and post it here? It should list what data you have.
```
 pyard-status
-------------------------------------------
IMGT DB Version: Latest (3520)
You're up to date. 3520 is the most recent version.
File: /var/folders/nm/nyjkgrfn3fg207v5z5rz1w8m0000gp/T/pyard/pyard-Latest.sqlite3
Size: 558.89MB
-------------------------------------------
|Table Name          |Rows                |
|-----------------------------------------|
|dup_g               |                  67|
|dup_lgx             |                   1|
|g_group             |               14445|
|p_group             |               21157|
|lgx_group           |               14445|
|exon_group          |               13140|
|p_not_g             |                1690|
|xx_codes            |                1995|
|who_group           |               36036|
|alleles             |               39386|
|exp_alleles         |                  84|
|who_alleles         |               37068|
|mac_codes           |             1113880|
-------------------------------------------
```

**Comment by pbashyal-nmdp** [comment]
Thanks for testing it and reporting the issue. It'll be part of `py-ard` with the next release of `1.0.1`.
