### ISSUE TITLE
Redux with the "lg", "lgx", and "G" option returns incorrect designation for "B*56:01" for IMGTHLA database version 3.51.0

### ISSUE THREAD

**Issue by gbiagini** [nmdp-bioinformatics/py-ard#232]
`ard.redux("B*56:01","lg")` returns `B*55:134g` instead of `B*56:01g`

Similar output is returned with the "lgx" and "G" options.

`ard.redux("B*56:01","lgx")` returns `B*55:134`

`ard.redux("B*56:01","G")` returns `B*55:134:01G` - Notably, B*55:134 does not have a three-field equivalent, so this seems to be an artificial composite of the actual G group and first listed allele.

This is likely due to the listing of the `B*56:01:01G` group in hla_nom_g.txt, if I had to guess:

B*;55:134/56:01:01:01/56:01:01:02/56:01:01:03/56:01:01:04/56:01:01:05S/56:01:01:06/56:01:01:07/56:01:01:08/56:01:01:09/56:01:01:10/56:01:01:11/56:01:01:12/56:01:01:13/56:01:01:14/56:01:01:15/56:01:01:16/56:01:10/56:01:17/56:01:18/56:24/56:40/56:55:01:02/56:68/56:69/56:70/56:72/56:79/56:83/56:90;56:01:01G

I haven't tested for other alleles, but I suspect that similar situations may occur if the G group designation in hla_nom_g.txt does not begin with the allele for which the G group is named.

These results were returned with the pre-release version (1.0.0) of py-ard on IMGTHLA dbversion 3.51.0 (`pyard.init('3510')`.

**Comment by gbiagini** [comment]
It looks like the "B*55:134" allele was named in error, and has since been updated. This was reported in an issue on the IMGTHLA repository: https://github.com/ANHIG/IMGTHLA/issues/330

From Deleted_alleles.txt: "HLA37168,B*55:134,Sequence named in error and renamed B*56:92 (February 2023)"

I'll clear my cache and see if the issue persists.

**Comment by gbiagini** [comment]
The issue does indeed persist after running `pyard-import --imgt-version 3510 --re-install` then attempting `ard.redux('B*56:01','lg')`

**Comment by mmaiers-nmdp** [comment]
I looked in 3.52.0 and the G table no longer has “B*55:134” so if you move to that version it will reduce to “B*56:01” again.

**Comment by mmaiers-nmdp** [comment]
> I looked in 3.52.0 and the G table no longer has ‘B_55:134’ so if you move to that version it will reduce to ‘B_56:01’ again.

**Comment by gbiagini** [comment]
Thanks for the clarification. 

Given that this is intended behavior, I'll go ahead and close the issue.
