### ISSUE TITLE
Issues in Serology Redux

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/py-ard#246]
Hi @pbashyal-nmdp,

Sorry for the delay in getting back to you; I finally got a chance to test it out and discuss with my PI. Overall I really like this feature and it works much more consistently than the lookup table I'd been using previously. We have a few points of feedback that you might still consider:

- We reduced all the alleles in the [Eurotransplant HLA tables](https://etrl.eurotransplant.org/resources/hla-tables/) with `py-ard` and checked for any differences, and found quite a few, mostly for HLA-B and DR. Sometimes this is simply a matter of debate, but we also found some that are potentially incorrect. Some examples:
  - `B*15:10` reduces to `B15/B62/B70/B71`; we think this should only be `B71(70)`
  - `B*15:11` reduces to `B15/B70/B75`; we think `B70` shouldn't be in there
  - `DRB1*07:34` doesn't reduce to anything (returns empty string); we think this should be a `DR7`
  -  Similarly, `DRB3*01:16` doesn't reduce to anything (returns empty string); we think this should be a `DR52`
 
  If you'd like I can send you the full list of examples. We checked the examples above against [Marsh et al. (2010)](https://doi.org/10.1111/j.1399-0039.2010.01466.x) and the current version of [rel_dna_ser.txt](https://github.com/ANHIG/IMGTHLA/blob/Latest/wmda/rel_dna_ser.txt).

- It could be useful to return both the split and the broad, but I'm not sure the `/` notation makes the most sense in this context. What `A25` (split) is to `A10` (broad) is not quite the same as what say `C*01:02` is to `C*01:03` in `C*01:02/C*01:03`. There's also no way to tell which is the split and which is the broad. You could also consider returning only splits if they exist, and otherwise the broad?

- Relatedly, if the input is already serology, the behaviour seems inconsistent. For example, `A25` is reduced to `A25/A10` (split and broad), but "reduction" of `DQ7` just returns itself, without the broad (`DQ3`).

Hope this is helpful and points to some potential areas for improvement. Thanks again!

_Originally posted by @lcreteig in https://github.com/nmdp-bioinformatics/py-ard/issues/229#issuecomment-1623956120_

**Comment by pbashyal-nmdp** [comment]
Thanks again for doing an extensive testing.

> * `B*15:10` reduces to `B15/B62/B70/B71`; we think this should only be `B71(70)`

Looks like a bug that is not checking for inclusion correctly. 

`B62` doesn't belong in the list but `B15` should. When checking for 2 field alleles, as they could be ARD reduced, we currently check for all alleles that could be reduced to the same 2 field allele. The `B*15:455`, `B*15:503` and `B*15:506` alleles of `B15` reduce to `B*15:10`.
```
$ pyard --gl 'B*15:455' -r 'lgx'
B*15:10
$ pyard --gl 'B*15:503' -r 'lgx'
B*15:10
$ pyard --gl 'B*15:506' -r 'lgx'
B*15:10
```

> * `B*15:11` reduces to `B15/B70/B75`; we think `B70` shouldn't be in there

Similarly `B70` includes `B*15:284`, `B*15:305`, `B*15:367` and `B*15:662` which reduce to `B*15:11`.

I'll follow up on the other issues.

**Comment by pbashyal-nmdp** [comment]
> * `DRB1*07:34` doesn't reduce to anything (returns empty string); we think this should be a `DR7`

`DR7` doesn't have `DRB1*07:34` but does have `DRB1*07:34:01` and `DRB1*07:34:02` which both reduce  to `DRB1*07:01`. When querying with 2 field allele  `DRB1*07:34`, it doesn't match.

```
$ pyard --gl "DRB1*07:34:01" -r 'lgx'
DRB1*07:01
$ pyard --gl "DRB1*07:34:02" -r 'lgx'
DRB1*07:01
```

**Comment by pbashyal-nmdp** [comment]
> * Similarly, `DRB3*01:16` doesn't reduce to anything (returns empty string); we think this should be a `DR52`

This one is a bug for which I will have a fix.

**Comment by pbashyal-nmdp** [comment]
> * If you'd like I can send you the full list of examples.

That would be great!

**Comment by pbashyal-nmdp** [comment]
> * Relatedly, if the input is already serology, the behaviour seems inconsistent. For example, `A25` is reduced to `A25/A10` (split and broad), but "reduction" of `DQ7` just returns itself, without the broad (`DQ3`).

Hmm.. They report both values to me.
```
$ pyard --gl "DQ7" -r 'S'
DQ3/DQ7
$ pyard --gl "A25" -r 'S'
A10/A25
```
and through code:
```
>>> import pyard
>>> ard = pyard.init()
>>> ard.redux('DQ7', 'S')
'DQ3/DQ7'
>>> ard.redux('A25', 'S')
'A10/A25'
```

**Comment by pbashyal-nmdp** [comment]
> * It could be useful to return both the split and the broad, but I'm not sure the `/` notation makes the most sense in this context. What `A25` (split) is to `A10` (broad) is not quite the same as what say `C*01:02` is to `C*01:03` in `C*01:02/C*01:03`. There's also no way to tell which is the split and which is the broad. You could also consider returning only splits if they exist, and otherwise the broad?

The `/` operator is the allele ambiguity character from GL String. The `A10/A25` signifies it could be part of broad or split.
You can also verify what the broad/splits are with `pyard --splits`:
```
$ pyard --splits A10
A10 = A25/A26/A34/A66
$ pyard --splits A25
A10 = A25/A26/A34/A66
```

or in Python:
```
>>> import pyard
>>> ard = pyard.init()
>>> pyard.find_broad_splits('A10')
('A10', ['A25', 'A26', 'A34', 'A66'])
```
Though this will become `ard.find_broad_splits('A10')` in the next update as it's currently a bit awkward.

**Comment by lcreteig** [comment]
> > * If you'd like I can send you the full list of examples.
> 
> That would be great!

Here it is: [downscaling_ipd_vs_etrl_v2_for-nmdp.csv](https://github.com/nmdp-bioinformatics/py-ard/files/12011438/downscaling_ipd_vs_etrl_v2_for-nmdp.csv). These are all the rows from the [ETRL lookup tables](https://etrl.eurotransplant.org/resources/hla-tables/) that are in use in our transplant region, where `pyard` returns a different serological equivalent than the broad/split from the table. I've also asked my PI (who's a transplant immunologist) to go over some of them; their comments are in the final column. 

N.B. The vast majority of these are not correct/incorrect per se, but just the result of different choices. But the ones you did consider to be bugs are also in there, so it could be that there are a few more.

**Comment by pbashyal-nmdp** [comment]
> The only risk is if two alleles with identical ARS AA sequence have different mapping but that would be nonsense

I verified that no 2 alleles that were reduced to `lgx` map to 2 different "full" alleles.  But the process did discover an issue #251

**Comment by pbashyal-nmdp** [comment]
Closing this as all the issues in [this milestone](https://github.com/nmdp-bioinformatics/py-ard/milestone/9) are complete as of `1.0.7`. If new bugs are found, please file an issue.
