### ISSUE TITLE
lookup_mac() and expand_mac() are not (always) reversible

### ISSUE THREAD

**Issue by lcreteig** [nmdp-bioinformatics/py-ard#249]
This one works:

```python
>>> ard.lookup_mac(ard.expand_mac('A*02:HBMC'))
'A*02:HBMC'
```
But this one does not:

```python
>>> ard.lookup_mac(ard.expand_mac('A*01:AABJE'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/code/py_ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 737, in lookup_mac
    raise InvalidMACError(f"{allelelist_gl} does not have a MAC.")
pyard.exceptions.InvalidMACError: Invalid MAC Code: A*01:01/A*01:23/A*01:98/A*01:100/A*36:04 does not have a MAC.
```

Note that the GL string returned by `expand_mac()` also differs from https://hml.nmdp.org/MacUI/; the latter returns an extra (short)null allele: `A*01:01/A*01:01N/A*01:23/A*01:98/A*01:100/A*36:04`. However this version is also not accepted by `lookup_mac()`:

```python
ard.lookup_mac('A*01:01/A*01:01N/A*01:23/A*01:98/A*01:100/A*36:04')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lreteig/code/py_ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 737, in lookup_mac
    raise InvalidMACError(f"{allelelist_gl} does not have a MAC.")
pyard.exceptions.InvalidMACError: Invalid MAC Code: A*01:01/A*01:01N/A*01:23/A*01:98/A*01:100/A*36:04 does not have a MAC.
```

Or is this expected behavior? I stumbled upon this by accident; not sure if/how many other MACs exhibit this behavior. 

This is `pyard` version 1.0.0. and IPD-IMGT/HLA release 3520 (currently the most recent).

**Comment by mmaiers-nmdp** [comment]
This is a behavior of the MAC system implemented at https://hml.nmdp.org/MacUI/.

If you enter `A*01:AABJE` into the "Decode MAC" window and paste the result into the Encode MAC window and use the "Lookup" button it will report that `A*01:01N` is not a valid allele.

The problem is that `A*01:01N` is not a valid allele.  The MAC system does support them but the recommendation is to not use them.

Not only should this allele be avoided but also MACs that encode them like `A*01:AABJE` should also be avoided.

I think its is safe to say that the "round trip" behavior of `A*02:HBMC` works because it doesn't use invalid alleles.
And that round trip behavior is not supported for MAC designations that include invalid alleles.

**Comment by lcreteig** [comment]
I just discovered another example that's making me wonder if there's more to it. 

"Round-trip behaviour" as described above by @mmaiers-nmdp works for `A*68:AJEBX` on <https://hml.nmdp.org/MacUI/>: that system is perfectly happy to first decode and than encode the result, and does not complain of invalid alleles.

But it fails for py-ard:

```python
ard.lookup_mac(ard.expand_mac("A*68:AJEBX"))
File "~/code/py_ard/venv/lib/python3.11/site-packages/pyard/ard.py", line 867, in lookup_mac
    raise InvalidMACError(f"{allelelist_gl} does not have a MAC.")
pyard.exceptions.InvalidMACError: Invalid MAC Code: A*68:01/A*68:07/A*68:08/A*68:11N/A*68:17/A*68:19/A*68:21/A*68:24/A*68:32/A*68:33/A*68:37/A*68:38/A*68:47/A*68:52/A*68:55/A*68:66/A*68:69/A*68:70/A*68:76/A*68:91/A*68:93/A*68:95/A*68:96/A*68:98/A*68:100/A*68:101/A*68:102/A*68:103/A*68:107/A*68:111/A*68:112/A*68:114/A*68:116/A*68:118/A*68:119/A*68:120N/A*68:121/A*68:123/A*68:132 does not have a MAC.
```

The decoding result is the same for py-ard and <https://hml.nmdp.org/MacUI/> (unlike `A*01:AABJE`, the example I gave previously), so the difference seems to be in the lookup/encoding. I'm using IPD-IMGT/HLA db 3.54.0 on both py-ard and the website.

**Comment by pbashyal-nmdp** [comment]
You're right, `A*68:AJEBX` should be able to decode/encode. I'll create an issue to work on this.

**Comment by pbashyal-nmdp** [comment]
Hello @lcreteig ,

The latest release `py-ard version: 1.1.2` should have the fix for this issue.
