### ISSUE TITLE
Provide a vignette for determining if two HLA typings are high resolution matched

### ISSUE THREAD

**Issue by lgragert** [nmdp-bioinformatics/py-ard#277]
Start with one typing a P group level and one typing reported at G group level and illustrate the process for determining if the two genotypes are high resolution matched based on NMDP standards.

Sometimes the first two fields of the P group and the first two fields of the G group could be different, so I think you'd want to standardize both typings to the P group level first, then compare first two fields? Or is there an even easier way to do it?

**Comment by pbashyal-nmdp** [comment]
The Magenta Service provides "Research Match Grades" (`HM`, `Hmm`, `IM`, `Imm`) based on CWD reduction of the typings. 
See: https://magenta.nmdp.org/

Is that workable for you ?

**Comment by lgragert** [comment]
Magenta is nice - we may use this API for generating lab reports because it handles the cases where there is still some ambiguity in the typing - Is there good documentation yet for Magenta?  For assessing alternative genotypes, is it based on CWD 2.0 or CIWD 3.0?

**Comment by pbashyal-nmdp** [comment]
It's using py-ard's  [CWD2](https://github.com/nmdp-bioinformatics/py-ard/blob/master/pyard/CWD2.csv) mapping and [CWD reductions](https://github.com/nmdp-bioinformatics/py-ard?tab=readme-ov-file#cwd-reduction).

Not much external documentation yet. Also the Magenta's use and future is in flux right now.

**Comment by lgragert** [comment]
Aha, so that means Magenta is not useful for determining if a typing meets NMDP/ASHI standards for high resolution typing.

NMDP/ASHI standards are based on CIWD 3.0, not CWD 2.0.
 
Definition of “High resolution typing” in current ASHI standards:
 
“High resolution typing: A high-resolution HLA genotype is reported in molecular HLA nomenclature to at least the second field, and may include P or G group designations. A high resolution HLA genotype may contain either a) only one unambiguously assigned genotype or b) multiple alternative genotypes if only one combination includes common and/or intermediate alleles (CIWD version 3.0.0), with the exception of null alleles; alternative genotype combinations containing a null allele listed as either common, intermediate, or well-documented must be resolved.”

**Comment by pbashyal-nmdp** [comment]
Bummer.

Closing this fow now as it's not `py-ard` specific.
