### ISSUE TITLE
Import error py-ard 1.0.4 using Python 3.11.5

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#278]
```
> import pyard

util.py", line 27, in <module>
    from typing import GenericMeta
ImportError: cannot import name 'GenericMeta' from 'typing' 
```

**Comment by pbashyal-nmdp** [comment]
I think you installed `pyard` and not `py-ard`. There's no `util.py` in `py-ard`.

I'll see if installing `pyard` can generate a warning.

**Comment by mmaiers-nmdp** [comment]
you are correct sir.   I had both installed somehow.

**Comment by pbashyal-nmdp** [comment]
Updated the old project `pyARD` project to alert you to use `py-ard` if you happen to mistype it. https://pypi.org/project/pyard/
