### ISSUE TITLE
Force 'lgx' reduction before 'S'?

### ISSUE THREAD

**Issue by lcreteig** [nmdp-bioinformatics/py-ard#290]
Hi @pbashyal-nmdp,

Thanks for all your latest improvements to the serology reduction feature! I tried it out and everything looks good to me now. 

I had one final question about an issue I originally raised, about the serological equivalent for `DRB1*07:34`. This could be considered `DR7`, but py-ard currently returns an empty string. You then responded the following:

> `DR7` doesn't have `DRB1*07:34` but does have `DRB1*07:34:01` and `DRB1*07:34:02` which both reduce  to `DRB1*07:01`. When querying with 2 field allele  `DRB1*07:34`, it doesn't match.
>
> ```
> $ pyard --gl "DRB1*07:34:01" -r 'lgx'
> DRB1*07:01
> $ pyard --gl "DRB1*07:34:02" -r 'lgx'
> DRB1*07:01
> ```
_Originally posted by @pbashyal-nmdp in https://github.com/nmdp-bioinformatics/py-ard/issues/246#issuecomment-1629680828_

Wouldn't a potential solution for cases like this be to always do a reduction with `lgx` mode first? I believe you might have tried that in #252, but I couldn't quite follow why you decided not to pursue this in the end. So, feel free to disregard if this is not a sensible suggestion.

I did try it out and noticed that while it does "solve" the DR7 case above, it does have some potentially unwanted effects, such as:

- Some null alleles suddenly do get a serological equivalent:
  ```python
  ard.redux(ard.redux("DRB4*01:03N", 'lgx'), 'S')
  # >>> 'DR53'
  ```

- Sometimes it errors because lgx reduction returns an invalid allele:
  ```python
  ard.redux(ard.redux("A*11:XX", 'lgx'),'S')
  InvalidAlleleError: Invalid Allele: A*11:403 is not a valid Allele
  ```

**Comment by pbashyal-nmdp** [comment]
Hello Leon,

Thank you for checking the issues again.

> Sometimes it errors because lgx reduction returns an invalid allele:

Yes, it's unfortunate some alleles disappear with different versions of IPD db. You can turn on **non-strict** mode which will validate alleles that are valid with an expression character. eg. `A*11:403` is valid for `A*11:403N`.

```
>>> ard = pyard.init(config={'strict': False})
>>> ard.redux(ard.redux("A*11:XX", 'lgx'),'S')
'A11'
```

**Comment by pbashyal-nmdp** [comment]
> Some null alleles suddenly do get a serological equivalent:

Yes, unfortunately as you saw with reductions, round trips can't be guaranteed.

**Comment by pbashyal-nmdp** [comment]
Yes, our previous proposed solution was to try and reduce all the serological equivalents to be in `lgx` format, but when I did that, I noticed that we don't get the same reduction when we reduce to `G` for the same serology. Sorry, my explanation wasn't clear. 

```
>>> ard.redux('DR7', 'G')
'DRB1*07:01:01G/DRB1*07:01:02/DRB1*07:01:03/DRB1*07:01:04/DRB1*07:01:05/DRB1*07:01:06/DRB1*07:01:07/DRB1*07:01:08/DRB1*07:01:09/DRB1*07:01:10/DRB1*07:01:11/DRB1*07:01:12/DRB1*07:01:13/DRB1*07:01:14/DRB1*07:01:15/DRB1*07:01:16/DRB1*07:01:17/DRB1*07:01:19/DRB1*07:01:20/DRB1*07:01:22/DRB1*07:01:23/DRB1*07:01:24/DRB1*07:01:25/DRB1*07:01:26/DRB1*07:01:27/DRB1*07:01:31/DRB1*07:01:32/DRB1*07:03/DRB1*07:04/DRB1*07:05/DRB1*07:06/DRB1*07:07/DRB1*07:08/DRB1*07:09/DRB1*07:11/DRB1*07:12/DRB1*07:13/DRB1*07:14/DRB1*07:15/DRB1*07:16/DRB1*07:17/DRB1*07:18/DRB1*07:19/DRB1*07:20/DRB1*07:21/DRB1*07:22/DRB1*07:23/DRB1*07:24/DRB1*07:25/DRB1*07:27/DRB1*07:28/DRB1*07:29/DRB1*07:30/DRB1*07:31/DRB1*07:32/DRB1*07:33/DRB1*07:35/DRB1*07:36/DRB1*07:37/DRB1*07:38/DRB1*07:39/DRB1*07:40/DRB1*07:41/DRB1*07:42/DRB1*07:43/DRB1*07:44/DRB1*07:45/DRB1*07:46/DRB1*07:47/DRB1*07:48/DRB1*07:49/DRB1*07:50/DRB1*07:51/DRB1*07:52/DRB1*07:53/DRB1*07:54/DRB1*07:55/DRB1*07:56/DRB1*07:57/DRB1*07:59/DRB1*07:60/DRB1*07:61/DRB1*07:62/DRB1*07:63/DRB1*07:64/DRB1*07:65/DRB1*07:66/DRB1*07:67/DRB1*07:69/DRB1*07:70/DRB1*07:71/DRB1*07:73/DRB1*07:74/DRB1*07:75/DRB1*07:76/DRB1*07:77/DRB1*07:78/DRB1*07:80/DRB1*07:82/DRB1*07:83/DRB1*07:84/DRB1*07:86/DRB1*07:88/DRB1*07:89/DRB1*07:90/DRB1*07:91/DRB1*07:94/DRB1*07:97/DRB1*07:98/DRB1*07:99/DRB1*07:112/DRB1*07:114/DRB1*07:115/DRB1*07:120/DRB1*07:121/DRB1*07:123/DRB1*07:124/DRB1*07:125/DRB1*07:126/DRB1*07:127/DRB1*07:128/DRB1*07:131/DRB1*07:133/DRB1*07:137/DRB1*07:138/DRB1*07:140/DRB1*07:141/DRB1*07:142/DRB1*07:144/DRB1*07:146/DRB1*07:154'
>>> len(ard.redux('DR7', 'G').split('/'))
131
```

which differs if we use the `lgx` format to use as the base for `G` group reduction.

```
>>> ard.redux(ard.redux('DR7', 'lgx'), 'G')
'DRB1*07:01:01G/DRB1*07:03/DRB1*07:04/DRB1*07:05/DRB1*07:06/DRB1*07:07/DRB1*07:08/DRB1*07:09/DRB1*07:11/DRB1*07:12/DRB1*07:13/DRB1*07:14/DRB1*07:15/DRB1*07:16/DRB1*07:17/DRB1*07:18/DRB1*07:19/DRB1*07:20/DRB1*07:21/DRB1*07:22/DRB1*07:23/DRB1*07:24/DRB1*07:25/DRB1*07:27/DRB1*07:28/DRB1*07:29/DRB1*07:30/DRB1*07:31/DRB1*07:32/DRB1*07:33/DRB1*07:35/DRB1*07:36/DRB1*07:37/DRB1*07:38/DRB1*07:39/DRB1*07:40/DRB1*07:41/DRB1*07:42/DRB1*07:43/DRB1*07:44/DRB1*07:45/DRB1*07:46/DRB1*07:47/DRB1*07:48/DRB1*07:49/DRB1*07:50/DRB1*07:51/DRB1*07:52/DRB1*07:53/DRB1*07:54/DRB1*07:55/DRB1*07:56/DRB1*07:57/DRB1*07:59/DRB1*07:60/DRB1*07:61/DRB1*07:62/DRB1*07:63/DRB1*07:64/DRB1*07:65/DRB1*07:66/DRB1*07:67/DRB1*07:69/DRB1*07:70/DRB1*07:71/DRB1*07:73/DRB1*07:74/DRB1*07:75/DRB1*07:76/DRB1*07:77/DRB1*07:78/DRB1*07:80/DRB1*07:82/DRB1*07:83/DRB1*07:84/DRB1*07:86/DRB1*07:88/DRB1*07:89/DRB1*07:90/DRB1*07:91/DRB1*07:94/DRB1*07:97/DRB1*07:98/DRB1*07:99/DRB1*07:112/DRB1*07:114/DRB1*07:115/DRB1*07:120/DRB1*07:121/DRB1*07:123/DRB1*07:124/DRB1*07:125/DRB1*07:126/DRB1*07:127/DRB1*07:128/DRB1*07:131/DRB1*07:133/DRB1*07:137/DRB1*07:138/DRB1*07:140/DRB1*07:141/DRB1*07:142/DRB1*07:144/DRB1*07:146/DRB1*07:154'
>>> len(ard.redux(ard.redux('DR7', 'lgx'), 'G').split('/'))
105
```

The solution might be to have both and choose based on the data. I'll take a look at it again.
