### ISSUE TITLE
"lgx" and "lg" should only return 2-fields

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#40]
```
 >>> ard.redux_gl('DRB1*14:06:01', "lgx")
'DRB1*14:06:01'

>>> ard.redux_gl('DRB1*14:05:01', "lgx")
'DRB1*14:05'

```

14:06:01 returns 3-field because this allele is not in a G group 
14:05:01 is so it returns 2-field

14:06:01 should return 2-field for "lgx" and "lg"

**Comment by pbashyal-nmdp** [comment]
**Initial investigation**
In both cases, they reach the following line in `redux` function:
https://github.com/nmdp-bioinformatics/py-ard/blob/ecff778bdb59af5f2abdfa676cfbe591e345cb57/pyard/pyard.py#L409
`'DRB1*14:05:01'` is found in `self._lgx` and it's `lgx` variant is returned `return self.lgx[allele]`
while
`'DRB1*14:06:01'` is not found in `self._lgx` and just returns `return allele`

**_Next Step_**
`'DRB1*14:06:01'` needs to be populated in `self._lgx`

**Comment by amadboul-nmdp** [comment]
This is a good first issue to address :)
