### ISSUE TITLE
Validation: incorrect processing of MAC designations 

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/py-ard#83]
```
>>> ard.redux_gl("C*05:ARAX", "lg")
'C*05:ARAXg'
>>> ard.redux_gl("C*05:ARAXBUG", "lg")
'C*05:ARAXBUg'
>>> ard.redux_gl("C*05:ARAXBUGSUCKS", "lg")
'C*05:ARAXBUGSUCKSg'
```

All three cases should return invalid MAC.
Note what the 2nd case did with the "G"

**Comment by pbashyal-nmdp** [comment]
Currently validation of invalid data is pretty minimal. It's in my TODO to add more validation before we get to `1.0.0` :) 
If py-ard currently can't validate, it returns an empty string `''`. Raising  `ValueError` will be inconistent to how it's working with other redux failures.

Per `Cw`, we had decided we wouldn't add support for Working Committee version of the Serology. That's changed ?
